### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mathanamathav** [drMy5tery/Trust-Me-Bro#22]
LOGO : 
![Black and Purple Gaming Avatar Logo](https://github.com/drMy5tery/Trust-Me-Bro/assets/62739618/d4db433c-ae1c-49e6-95d0-bb9623b39e8c)

ICON :
![2](https://github.com/drMy5tery/Trust-Me-Bro/assets/62739618/e6c6f138-1acd-44a1-a2fa-72c63795a9f0)

**Comment by mathanamathav** [comment]
![image](https://github.com/drMy5tery/Trust-Me-Bro/assets/62739618/8c5ef329-b050-4711-8af9-31bc1357bdb2)

**Comment by mathanamathav** [comment]
@drMy5tery

**Comment by drMy5tery** [comment]
💪🏻🔥
